// File generated by FlutterFire CLI / configured from GoogleService-Info.plist
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZxOTUQzdiJyn9-LDsfnkJdTOPWdBYDI',
    appId: '1:749192968385:ios:933382c11815273d0cfc40',
    messagingSenderId: '749192968385',
    projectId: 'aarogya-5abf6',
    storageBucket: 'aarogya-5abf6.firebasestorage.app',
    iosBundleId: 'com.omkar.aarogya',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhZ8aQ5Oew8KVtD_7dzIdYzDy_gC1ClVI',
    appId: '1:749192968385:android:79adc2e5ddb084110cfc40',
    messagingSenderId: '749192968385',
    projectId: 'aarogya-5abf6',
    storageBucket: 'aarogya-5abf6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA528CbkznObd2exl_tziERjiuKIIRX7fU',
    appId: '1:749192968385:web:4ef54147cbff92da0cfc40',
    messagingSenderId: '749192968385',
    projectId: 'aarogya-5abf6',
    authDomain: 'aarogya-5abf6.firebaseapp.com',
    storageBucket: 'aarogya-5abf6.firebasestorage.app',
    measurementId: 'G-QK6B9L9NSC',
  );
}
